### ISSUE TITLE
Unmanaged switches will always restart after flashing this firmware

### ISSUE THREAD

**Issue by WowRouter** [up-n-atom/SWTG118AS#2]
Unmanaged switches will always restart after flashing this firmware. I heard that a pull-up resistor needs to be changed. Does anyone know how to change it?

**Comment by up-n-atom** [comment]
I made a post on sth https://forums.servethehome.com/index.php?threads/horaco-2-5gbe-managed-switch-8-x-2-5gbe-1-10gb-sfp.41571/post-428606
