### ISSUE TITLE
A bit of detail on flash memory - SWTG124AS v1.0

### ISSUE THREAD

**Issue by giver3** [up-n-atom/SWTG118AS#3]
I have some information that may be of use to someone.
Applies to the model: SWTG124AS v1.0, perhaps other variants as well.

Flash memory: FM25Q16A (nor, 16M-bit serial memory, SOP8-208mil).
Initially the clock frequency is 20MHz (standard read, 0x03), but after a while it switches to approx. 60 MHz (fast read - 0x0B).

Unique ID (0x4b): In the two exemplars I was able to read it was: 0x10, 0x09, 0x3f, 0x30, 0xd4, XX, XX, XX (XX - probably any value)
Security Section (0x48): 16 Bytes, Same value in both exemplars. The data looks like 8 Bytes written as HEX characters from ASCII codes. Example: 0x61h, 0x64h = 0xad

Differences in binary files (after dumping the contents of the flash memory into a file)
Apart from configuration differences, the main differences are in the address area: 0x000fa8c2

I gathered this information because I wanted to repair the switch after a failed firmware update and damage to the flash memory chip during desoldering. I have now learnt how best to desolder this memory and have done it over 10 times without damage.

Copying the one to one memory image does not help the boot. Even after copying the security section. Probably the problem is with a different Unique ID or the correct value (taking into account other Unique IDs).

Perhaps someone can help me to fix this switch.

**Comment by up-n-atom** [comment]
Sorry for the late reply, there is some development that can help you recovery in #4 and has been confirmed to work at:

https://forums.servethehome.com/index.php?threads/horaco-2-5gbe-managed-switch-8-x-2-5gbe-1-10gb-sfp.41571/post-428282

**Comment by giver3** [comment]
Thank you for in formation. I will try to apply it.
